<?php
// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, "http://54.88.201.242:50070/webhdfs/v1/?op=LISTSTATUS");
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}

echo $result;
echo "<br>";
$jsonStuff = json_decode($result);
echo $jsonStuff['FileStatuses'];

curl_close ($ch);
?>