<?php
// $ch = curl_init();

// curl_setopt($ch, CURLOPT_URL, "ec2-54-88-201-242.compute-1.amazonaws.com:50070/webhdfs/v1/". $_GET['vid'] ."?op=OPEN");
// curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);

// $result = curl_exec($ch);
// if (curl_errno($ch)) {
//     echo 'Error:' . curl_error($ch);
// }
// curl_close ($ch);

// echo $result;


$vid = $_GET['vid'];
$array = [
    "ip-172-31-26-8.ec2.internal:50075" => "100.26.36.129:50075",
    "ip-172-31-31-46.ec2.internal:50075" => "34.203.213.13:50075",
    "ip-172-31-31-55.ec2.internal:50075" => "34.224.89.168:50075",
];

// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, "ec2-54-88-201-242.compute-1.amazonaws.com:50070");
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 0);
curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 0);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close ($ch);

$jsonStuff = json_decode($result, true);

echo "<!-- " . $result . " -->";
// echo "THIS IS THE RESULT" . $jsonStuff;

$array["ip-172-31-26-8.ec2.internal:50075"];

// $command = escapeshellcmd("./php/download.py videos/$vid");
// $run = shell_exec($command);
// echo $run;

?>