<?php
// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/

$path = '/var/www/html/videos/';
$files = array_diff(scandir($path), array('.', '..'));

foreach($files as $file){
    echo '<a href="watch.php?vid='. $file .'" class="list-group-item list-group-item-action active videoListItem">
            '. $file .'
        </a>';
}

curl_close ($ch);
?>
